# Sensors for esp32_p1meter to be used in Home Assistant
# In configuration.yaml file add following line to make sensors appear in HA:
# mqtt: !include mqtt.yaml
sensor:
  - name: P1 Meter Clock Raw
    unique_id: p1_meter_clock_raw
    state_topic: "p1_meter/sensor/clock"
    icon: "mdi:clock"
  - name: P1 Meter Clock Timestamp
    unique_id: p1_meter_clock_timestamp
    state_topic: "p1_meter/sensor/clock"
    value_template: >
      {{strptime(value | regex_findall_index("\d*"), '%y%m%d%H%M%S') | as_timestamp}}
  - name: P1 Meter Clock Date and Time
    unique_id: p1_meter_clock_datetime
    state_topic: "p1_meter/sensor/clock"
    value_template: >
      {{strptime(value | regex_findall_index("\d*"), '%y%m%d%H%M%S')}}

  - name: P1 Meter Active energy import (+A)
    unique_id: p1_meter_active_energy_import
    state_topic: "p1_meter/sensor/active_energy_import"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "kWh"
    suggested_display_precision: 3

  - name: P1 Meter Active energy import (+A) rate 1
    unique_id: p1_meter_active_energy_import_rate_1
    state_topic: "p1_meter/sensor/active_energy_import_rate_1"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "kWh"
    suggested_display_precision: 3
  - name: P1 Meter Active energy import (+A) rate 2
    unique_id: p1_meter_active_energy_import_rate_2
    state_topic: "p1_meter/sensor/active_energy_import_rate_2"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "kWh"
    suggested_display_precision: 3

  - name: P1 Meter Active energy export (-A)
    unique_id: p1_meter_active_energy_export
    state_topic: "p1_meter/sensor/active_energy_export"
    device_class: "energy"
    state_class: "total_increasing"
    unit_of_measurement: "kWh"
    suggested_display_precision: 3

  - name: P1 Meter Reactive energy import (+R)
    unique_id: p1_meter_reactive_energy_import
    state_topic: "p1_meter/sensor/reactive_energy_import"
    device_class: "reactive_power"
    state_class: "total_increasing"
    unit_of_measurement: "var"
    suggested_display_precision: 3
  - name: P1 Meter Reactive energy export (-R)
    unique_id: p1_meter_reactive_energy_export
    state_topic: "p1_meter/sensor/reactive_energy_export"
    device_class: "reactive_power"
    state_class: "total_increasing"
    unit_of_measurement: "var"
    suggested_display_precision: 3

  - name: P1 Meter Instantaneous voltage L1
    unique_id: p1_meter_instantaneous_voltage_l1
    state_topic: "p1_meter/sensor/instantaneous_voltage_l1"
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
  - name: P1 Meter Instantaneous current L1
    unique_id: p1_meter_instantaneous_current_l1
    state_topic: "p1_meter/sensor/instantaneous_current_l1"
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: "A"
  - name: P1 Meter Instantaneous voltage L2
    unique_id: p1_meter_instantaneous_voltage_l2
    state_topic: "p1_meter/sensor/instantaneous_voltage_l2"
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
  - name: P1 Meter Instantaneous current L2
    unique_id: p1_meter_instantaneous_current_l2
    state_topic: "p1_meter/sensor/instantaneous_current_l2"
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: "A"
  - name: P1 Meter Instantaneous voltage L3
    unique_id: p1_meter_instantaneous_voltage_l3
    state_topic: "p1_meter/sensor/instantaneous_voltage_l3"
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"
  - name: P1 Meter Instantaneous current L3
    unique_id: p1_meter_instantaneous_current_l3
    state_topic: "p1_meter/sensor/instantaneous_current_l3"
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: "A"

  - name: P1 Meter Instantaneous net frequency; any phase
    unique_id: p1_meter_instantaneous_net_frequency_any_phase
    state_topic: "p1_meter/sensor/instantaneous_net_frequency_any_phase"
    device_class: "frequency"
    state_class: "measurement"
    unit_of_measurement: "Hz"

  - name: P1 Meter Instantaneous active import power (+A)
    unique_id: p1_meter_instantaneous_active_import_power
    state_topic: "p1_meter/sensor/instantaneous_active_import_power"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active import power (+A) in phase L1
    unique_id: p1_meter_instantaneous_active_import_power_in_phase_l1
    state_topic: "p1_meter/sensor/instantaneous_active_import_power_in_phase_l1"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active import power (+A) in phase L2
    unique_id: p1_meter_instantaneous_active_import_power_in_phase_l2
    state_topic: "p1_meter/sensor/instantaneous_active_import_power_in_phase_l2"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active import power (+A) in phase L3
    unique_id: p1_meter_instantaneous_active_import_power_in_phase_l3
    state_topic: "p1_meter/sensor/instantaneous_active_import_power_in_phase_l3"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"

  - name: P1 Meter Instantaneous active export power (+A)
    unique_id: p1_meter_instantaneous_active_export_power
    state_topic: "p1_meter/sensor/instantaneous_active_export_power"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active export power (-A) in phase L1
    unique_id: p1_meter_instantaneous_active_export_power_in_phase_l1
    state_topic: "p1_meter/sensor/instantaneous_active_export_power_in_phase_l1"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active export power (-A) in phase L2
    unique_id: p1_meter_instantaneous_active_export_power_in_phase_l2
    state_topic: "p1_meter/sensor/instantaneous_active_export_power_in_phase_l2"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
  - name: P1 Meter Instantaneous active export power (-A) in phase L3
    unique_id: p1_meter_instantaneous_active_export_power_in_phase_l3
    state_topic: "p1_meter/sensor/instantaneous_active_export_power_in_phase_l3"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"

  - name: P1 Meter Instantaneous reactive import power (+R)
    unique_id: p1_meter_instantaneous_reactive_import_power
    state_topic: "p1_meter/sensor/instantaneous_reactive_import_power"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive import power (+R) in phase L1
    unique_id: p1_meter_instantaneous_reactive_import_power_in_phase_l1
    state_topic: "p1_meter/sensor/instantaneous_reactive_import_power_in_phase_l1"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive import power (+R) in phase L2
    unique_id: p1_meter_instantaneous_reactive_import_power_in_phase_l2
    state_topic: "p1_meter/sensor/instantaneous_reactive_import_power_in_phase_l2"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive import power (+R) in phase L3
    unique_id: p1_meter_instantaneous_reactive_import_power_in_phase_l3
    state_topic: "p1_meter/sensor/instantaneous_reactive_import_power_in_phase_l3"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"

  - name: P1 Meter Instantaneous reactive export power (-R)
    unique_id: p1_meter_instantaneous_reactive_export_power
    state_topic: "p1_meter/sensor/instantaneous_reactive_export_power"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive export power (-R) in phase L1
    unique_id: p1_meter_instantaneous_reactive_export_power_in_phase_l1
    state_topic: "p1_meter/sensor/instantaneous_reactive_export_power_in_phase_l1"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive export power (-R) in phase L2
    unique_id: p1_meter_instantaneous_reactive_export_power_in_phase_l2
    state_topic: "p1_meter/sensor/instantaneous_reactive_export_power_in_phase_l2"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"
  - name: P1 Meter Instantaneous reactive export power (-R) in phase L3
    unique_id: p1_meter_instantaneous_reactive_export_power_in_phase_l3
    state_topic: "p1_meter/sensor/instantaneous_reactive_export_power_in_phase_l3"
    device_class: "reactive_power"
    state_class: "measurement"
    unit_of_measurement: "var"

  - name: P1 Meter Instantaneous Power factor (+A/+VA)
    unique_id: p1_meter_instantaneous_power_factor
    state_topic: "p1_meter/sensor/instantaneous_power_factor"
    device_class: "power_factor"
    state_class: "measurement"
  - name: P1 Meter Instantaneous power factor in phase L1
    unique_id: p1_meter_instantaneous_power_factor_in_phase_l1
    state_topic: "p1_meter/sensor/instantaneous_power_factor_in_phase_l1"
    device_class: "power_factor"
    state_class: "measurement"
  - name: P1 Meter Instantaneous power factor in phase L2
    unique_id: p1_meter_instantaneous_power_factor_in_phase_l2
    state_topic: "p1_meter/sensor/instantaneous_power_factor_in_phase_l2"
    device_class: "power_factor"
    state_class: "measurement"
  - name: P1 Meter Instantaneous power factor in phase L3
    unique_id: p1_meter_instantaneous_power_factor_in_phase_l3
    state_topic: "p1_meter/sensor/instantaneous_power_factor_in_phase_l3"
    device_class: "power_factor"
    state_class: "measurement"
  - name: P1 Meter Minimum Power factor (+A/+VA)
    unique_id: p1_meter_minimum_power_factor
    state_topic: "p1_meter/sensor/minimum_power_factor"
    device_class: "power_factor"
    state_class: "measurement"

  - name: P1 Meter Number of power failures in any phase
    unique_id: p1_meter_number_of_power_failures_in_any_phase
    state_topic: "p1_meter/sensor/number_of_power_failures_in_any_phase"
    state_class: "total_increasing"
  - name: P1 Meter Number of voltage sags in phase L1
    unique_id: p1_meter_number_of_voltage_sags_in_phase_l1
    state_topic: "p1_meter/sensor/number_of_voltage_sags_in_phase_l1"
    state_class: "total_increasing"
  - name: P1 Meter Number of voltage sags in phase L2
    unique_id: p1_meter_number_of_voltage_sags_in_phase_l2
    state_topic: "p1_meter/sensor/number_of_voltage_sags_in_phase_l2"
    state_class: "total_increasing"
  - name: P1 Meter Number of voltage sags in phase L3
    unique_id: p1_meter_number_of_voltage_sags_in_phase_l3
    state_topic: "p1_meter/sensor/number_of_voltage_sags_in_phase_l3"
    state_class: "total_increasing"

  - name: P1 Meter Number of voltage swells in phase L1
    unique_id: p1_meter_number_of_voltage_swells_in_phase_l1
    state_topic: "p1_meter/sensor/number_of_voltage_swells_in_phase_l1"
    state_class: "total_increasing"
  - name: P1 Meter Number of voltage swells in phase L2
    unique_id: p1_meter_number_of_voltage_swells_in_phase_l2
    state_topic: "p1_meter/sensor/number_of_voltage_swells_in_phase_l2"
    state_class: "total_increasing"
  - name: P1 Meter Number of voltage swells in phase L3
    unique_id: p1_meter_number_of_voltage_swells_in_phase_l3
    state_topic: "p1_meter/sensor/number_of_voltage_swells_in_phase_l3"
    state_class: "total_increasing"


  - name: P1 Meter Consumer Message text
    unique_id: p1_meter_consumer_message_text
    state_topic: "p1_meter/sensor/consumer_message_text"
